services:
  - type: web
    name: estim-chat
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: "https://estim-chat2.onrender.com"
      - key: MONGO_URI
        value: "mongodb+srv://estimuser:MBxd4nYXBueq8HKq@cluster0.8kt9y6n.mongodb.net/estimchat?retryWrites=true&w=majority"
      - key: JWT_SECRET
        value: "7744af9dddc4b98ec02c381150eaee77"
      - key: SESSION_SECRET
        value: "a0b71a8ebd95128cc2444bf90281e3e3"
      - key: GOOGLE_CLIENT_ID
        value: "237020081768-2vne4nisef7fenbntj9p5onp8k70nobg.apps.googleusercontent.com"
      - key: GOOGLE_CLIENT_SECRET
        value: "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"
      - key: GOOGLE_CALLBACK_URL
        value: "https://estim-chat2.onrender.com/api/auth/google/callback"

      - key: APPLE_CLIENT_ID
        value: ""
      - key: APPLE_TEAM_ID
        value: ""
      - key: APPLE_KEY_ID
        value: ""
      - key: APPLE_PRIVATE_KEY
        value: ""
      - key: APPLE_CALLBACK_URL
        value: ""

      - key: MAX_FILE_SIZE_MB
        value: "5"
